### PR TITLE
Update the API route names to be unique

### PR DESCRIPTION
**Pull request by jordn**
Impact of https://github.com/humanloop/hl-alpha/pull/4124

Screenshot 2024-09-30 at 17 14 00

### CODE REVIEW

**Comment by harry-humanloop** [comment]
inconsistency in the screenshot: "Update Log" under Prompt and "Update a Tool Log" under Tool. is this intentional?

also what does the SDK look like?

**Comment by jordn** [comment]
Fixed that. I ASSUME that the SDK stays the same

**Comment by jordn** [comment]
if approved please merge, will help SEO

**Comment by harry-humanloop** [comment]
have generated the sdk locally; it looks the same.

there are still minor inconsistencies such as:
- "Log to a Prompt". "Log to Tool".
- "Commit a Prompt Version". "Commit" (for Tool)
- "List Deployed Versions of a Prompt". "List Environments" (for Tool)

merging as this is an improvement

**Pull request merged**
